import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { format, resolveConfig } from 'prettier';
import { STAGE_OPERATOR_NAMES } from '@mongodb-js/mongodb-constants';

const iconsDir = join(__dirname, '..', 'src', 'icons');
const outFile = join(__dirname, '..', 'src', 'stage-icon-data.ts');

const knownStages = new Set<string>(STAGE_OPERATOR_NAMES);

function buildSource(): string {
  const entries = readdirSync(iconsDir)
    .filter((file) => file.endsWith('.svg'))
    .sort((a, b) => a.localeCompare(b))
    .map((file) => {
      const svg = readFileSync(join(iconsDir, file), 'utf8');
      const paths = [...svg.matchAll(/<path\b[^>]*\bd="([^"]+)"/g)];
      if (paths.length !== 1) {
        throw new Error(
          `Expected exactly one <path> in ${file}, found ${paths.length}`,
        );
      }
      const name = file.slice(0, -'.svg'.length);
      if (!knownStages.has(name)) {
        throw new Error(
          `${file} does not correspond to a known aggregation stage. ` +
            `Its name must match one of the stage operators in @mongodb-js/mongodb-constants.`,
        );
      }
      return `  ${JSON.stringify(name)}: ${JSON.stringify(paths[0][1])},`;
    });

  return (
    `// Generated by scripts/extract-icon-paths.ts. Do not edit by hand.\n\n` +
    `export const stageIconPaths = {\n${entries.join('\n')}\n} as const;\n`
  );
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');

  const config = await resolveConfig(outFile);
  const formatted = await format(buildSource(), {
    ...config,
    parser: 'typescript',
  });

  if (check) {
    if (readFileSync(outFile, 'utf8') !== formatted) {
      throw new Error(
        `${outFile} is out of date. Run \`npm run extract-icon-paths\` and commit the result.`,
      );
    }
    return;
  }

  writeFileSync(outFile, formatted);
}

main().catch((error) => {
  // eslint-disable-next-line no-console
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
