/**
 * The accumulators.
 */
const ACCUMULATORS = [
  {
    name: '$accumulator',
    value: '$accumulator',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '4.4.0',
  },
  {
    name: '$addToSet',
    value: '$addToSet',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '2.2.0',
  },
  {
    name: '$avg',
    value: '$avg',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '2.2.0',
    projectVersion: '3.2.0',
  },
  {
    name: '$bottom',
    value: '$bottom',
    firstStage: false,
    score: 1,
    meta: 'accumulator:bottom-n',
    version: '5.2.0',
  },
  {
    name: '$bottomN',
    value: '$bottomN',
    firstStage: false,
    score: 1,
    meta: 'accumulator:bottom-n',
    version: '5.2.0',
  },
  {
    name: '$covariancePop',
    value: '$covariancePop',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.0.0',
  },
  {
    name: '$covarianceSamp',
    value: '$covarianceSamp',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.0.0',
  },
  {
    name: '$count',
    value: '$count',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '5.0.0',
  },
  {
    name: '$derivative',
    value: '$derivative',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.0.0',
  },
  {
    name: '$denseRank',
    value: '$denseRank',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.0.0',
  },
  {
    name: '$documentNumber',
    value: '$documentNumber',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.0.0',
  },
  {
    name: '$expMovingAvg',
    value: '$expMovingAvg',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.0.0',
  },
  {
    name: '$first',
    value: '$first',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '2.2.0',
  },
  {
    name: '$firstN',
    value: '$firstN',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '5.1.0',
  },
  {
    name: '$integral',
    value: '$integral',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.0.0',
  },
  {
    name: '$last',
    value: '$last',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '2.2.0',
  },
  {
    name: '$lastN',
    value: '$lastN',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '5.2.0',
  },
  {
    name: '$max',
    value: '$max',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '2.2.0',
    projectVersion: '3.2.0',
  },
  {
    name: '$maxN',
    value: '$maxN',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '5.2.0',
  },
  {
    name: '$min',
    value: '$min',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '2.2.0',
    projectVersion: '3.2.0',
  },
  {
    name: '$minN',
    value: '$minN',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '5.2.0',
  },
  {
    name: '$push',
    value: '$push',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '2.2.0',
  },
  {
    name: '$rank',
    value: '$rank',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.0.0',
  },
  {
    name: '$stdDevPop',
    value: '$stdDevPop',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '3.2.0',
    projectVersion: '3.2.0',
  },
  {
    name: '$stdDevSamp',
    value: '$stdDevSamp',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '3.2.0',
    projectVersion: '3.2.0',
  },
  {
    name: '$shift',
    value: '$shift',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.0.0',
  },
  {
    name: '$sum',
    value: '$sum',
    firstStage: false,
    score: 1,
    meta: 'accumulator',
    version: '2.2.0',
    projectVersion: '3.2.0',
  },
  {
    name: '$top',
    value: '$top',
    firstStage: false,
    score: 1,
    meta: 'accumulator:top-n',
    version: '5.2.0',
  },
  {
    name: '$topN',
    value: '$topN',
    firstStage: false,
    score: 1,
    meta: 'accumulator:top-n',
    version: '5.2.0',
  },
  {
    name: '$locf',
    value: '$locf',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.3.0',
  },
  {
    name: '$linearFill',
    value: '$linearFill',
    firstStage: false,
    score: 1,
    meta: 'accumulator:window',
    version: '5.3.0',
  },
] as const;

export { ACCUMULATORS };
