/**
 * The BSON type aliases.
 */
const BSON_TYPE_ALIASES = [
  {
    name: 'double',
    value: 'double',
    label: 'double',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'string',
    value: 'string',
    label: 'string',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'object',
    value: 'object',
    label: 'object',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'array',
    value: 'array',
    label: 'array',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'binData',
    value: 'binData',
    label: 'binData',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'objectId',
    value: 'objectId',
    label: 'objectId',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'bool',
    value: 'bool',
    label: 'bool',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'date',
    value: 'date',
    label: 'date',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'null',
    value: 'null',
    label: 'null',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'double',
    value: 'double',
    label: 'double',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'regex',
    value: 'regex',
    label: 'regex',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'javascript',
    value: 'javascript',
    label: 'javascript',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'javascriptWithScope',
    value: 'javascriptWithScope',
    label: 'javascriptWithScope',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'int',
    value: 'int',
    label: 'int',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'timestamp',
    value: 'timestamp',
    label: 'timestamp',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'long',
    value: 'long',
    label: 'long',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'decimal',
    value: 'decimal',
    label: 'decimal',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'minKey',
    value: 'minKey',
    label: 'minKey',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
  {
    name: 'maxKey',
    value: 'maxKey',
    label: 'maxKey',
    firstStage: false,
    score: 1,
    meta: 'bson-type-aliases',
    version: '3.6.0',
  },
] as const;

export { BSON_TYPE_ALIASES };
