/**
 * The expression operators.
 */
const EXPRESSION_OPERATORS = [
  {
    name: '$abs',
    value: '$abs',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$accumulator',
    value: '$accumulator',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '4.4.0',
  },
  {
    name: '$add',
    value: '$add',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '2.2.0',
  },
  {
    name: '$allElementsTrue',
    value: '$allElementsTrue',
    firstStage: false,
    score: 1,
    meta: 'expr:set',
    version: '2.6.0',
  },
  {
    name: '$and',
    value: '$and',
    firstStage: false,
    score: 1,
    meta: 'expr:bool',
    version: '2.2.0',
  },
  {
    name: '$anyElementTrue',
    value: '$anyElementTrue',
    firstStage: false,
    score: 1,
    meta: 'expr:set',
    version: '2.6.0',
  },
  {
    name: '$arrayElemAt',
    value: '$arrayElemAt',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.2.0',
  },
  {
    name: '$arrayToObject',
    value: '$arrayToObject',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.4.4',
  },
  {
    name: '$binarySize',
    value: '$binarySize',
    firstStage: false,
    score: 1,
    meta: 'expr:obj',
    version: '4.4.0',
  },
  {
    name: '$bsonSize',
    value: '$bsonSize',
    firstStage: false,
    score: 1,
    meta: 'expr:obj',
    version: '4.4.0',
  },
  {
    name: '$ceil',
    value: '$ceil',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$cmp',
    value: '$cmp',
    firstStage: false,
    score: 1,
    meta: 'expr:comp',
    version: '2.2.0',
  },
  {
    name: '$concat',
    value: '$concat',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '2.4.0',
  },
  {
    name: '$concatArrays',
    value: '$concatArrays',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.2.0',
  },
  {
    name: '$cond',
    value: '$cond',
    firstStage: false,
    score: 1,
    meta: 'expr:cond',
    version: '2.6.0',
  },
  {
    name: '$dateAdd',
    value: '$dateAdd',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '5.0.0',
  },
  {
    name: '$dateDiff',
    value: '$dateDiff',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '5.0.0',
  },
  {
    name: '$dateFromParts',
    value: '$dateFromParts',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '3.6.0',
  },
  {
    name: '$dateFromString',
    value: '$dateFromString',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '3.6.0',
  },
  {
    name: '$dateSubtract',
    value: '$dateSubtract',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '5.0.0',
  },
  {
    name: '$dateToParts',
    value: '$dateToParts',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '3.6.0',
  },
  {
    name: '$dateToString',
    value: '$dateToString',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '3.6.0',
  },
  {
    name: '$dateTrunc',
    value: '$dateTrunc',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '5.0.0',
  },
  {
    name: '$dayOfMonth',
    value: '$dayOfMonth',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '2.2.0',
  },
  {
    name: '$dayOfWeek',
    value: '$dayOfWeek',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '2.2.0',
  },
  {
    name: '$dayOfYear',
    value: '$dayOfYear',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '2.2.0',
  },
  {
    name: '$dateToString',
    value: '$dateToString',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '3.0.0',
  },
  {
    name: '$divide',
    value: '$divide',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '2.2.0',
  },
  {
    name: '$eq',
    value: '$eq',
    firstStage: false,
    score: 1,
    meta: 'expr:comp',
    version: '2.2.0',
  },
  {
    name: '$exp',
    value: '$exp',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$filter',
    value: '$filter',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.2.0',
  },
  {
    name: '$first',
    value: '$first',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '4.4.0',
  },
  {
    name: '$floor',
    value: '$floor',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$function',
    value: '$function',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '4.4.0',
  },
  {
    name: '$getField',
    value: '$getField',
    firstStage: false,
    score: 1,
    meta: 'expr:get',
    version: '5.0.0',
  },
  {
    name: '$gt',
    value: '$gt',
    firstStage: false,
    score: 1,
    meta: 'expr:comp',
    version: '2.2.0',
  },
  {
    name: '$gte',
    value: '$gte',
    firstStage: false,
    score: 1,
    meta: 'expr:comp',
    version: '2.2.0',
  },
  {
    name: '$hour',
    value: '$hour',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '2.2.0',
  },
  {
    name: '$ifNull',
    value: '$ifNull',
    firstStage: false,
    score: 1,
    meta: 'expr:cond',
    version: '2.2.0',
  },
  {
    name: '$in',
    value: '$in',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.4.0',
  },
  {
    name: '$indexOfArray',
    value: '$indexOfArray',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.4.0',
  },
  {
    name: '$indexOfBytes',
    value: '$indexOfBytes',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '3.4.0',
  },
  {
    name: '$indexOfCP',
    value: '$indexOfCP',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '3.4.0',
  },
  {
    name: '$isArray',
    value: '$isArray',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.2.0',
  },
  {
    name: '$isNumber',
    value: '$isNumber',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '4.4.0',
  },
  {
    name: '$isoDayOfWeek',
    value: '$isoDayOfWeek',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '3.4.0',
  },
  {
    name: '$isoWeek',
    value: '$isoWeek',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '3.4.0',
  },
  {
    name: '$isoWeekYear',
    value: '$isoWeekYear',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '3.4.0',
  },
  {
    name: '$last',
    value: '$last',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '4.4.0',
  },
  {
    name: '$let',
    value: '$let',
    firstStage: false,
    score: 1,
    meta: 'expr:var',
    version: '2.6.0',
  },
  {
    name: '$literal',
    value: '$literal',
    firstStage: false,
    score: 1,
    meta: 'expr:literal',
    version: '2.6.0',
  },
  {
    name: '$lt',
    value: '$lt',
    firstStage: false,
    score: 1,
    meta: 'expr:comp',
    version: '2.2.0',
  },
  {
    name: '$lt',
    value: '$lte',
    firstStage: false,
    score: 1,
    meta: 'expr:comp',
    version: '2.2.0',
  },
  {
    name: '$ln',
    value: '$ln',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$log',
    value: '$log',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$log10',
    value: '$log10',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$map',
    value: '$map',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '2.6.0',
  },
  {
    name: '$mergeObjects',
    value: '$mergeObjects',
    firstStage: false,
    score: 1,
    meta: 'expr:obj',
    version: '3.6.0',
  },
  {
    name: '$meta',
    value: '$meta',
    firstStage: false,
    score: 1,
    meta: 'expr:text',
    version: '2.6.0',
  },
  {
    name: '$millisecond',
    value: '$millisecond',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '2.4.0',
  },
  {
    name: '$minute',
    value: '$minute',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '2.2.0',
  },
  {
    name: '$mod',
    value: '$mod',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '2.2.0',
  },
  {
    name: '$month',
    value: '$month',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '2.2.0',
  },
  {
    name: '$multiply',
    value: '$multiply',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '2.2.0',
  },
  {
    name: '$new',
    value: '$new',
    firstStage: false,
    score: 1,
    meta: 'expr:comp',
    version: '2.2.0',
  },
  {
    name: '$not',
    value: '$not',
    firstStage: false,
    score: 1,
    meta: 'expr:bool',
    version: '2.2.0',
  },
  {
    name: '$objectToArray',
    value: '$objectToArray',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.4.4',
  },
  {
    name: '$or',
    value: '$or',
    firstStage: false,
    score: 1,
    meta: 'expr:bool',
    version: '2.2.0',
  },
  {
    name: '$pow',
    value: '$pow',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$range',
    value: '$range',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.4.0',
  },
  {
    name: '$reduce',
    value: '$reduce',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.4.0',
  },
  {
    name: '$regexFind',
    value: '$regexFind',
    firstStage: false,
    score: 1,
    meta: 'expr:regex',
    version: '4.1.11',
  },
  {
    name: '$regexFindAll',
    value: '$regexFindAll',
    firstStage: false,
    score: 1,
    meta: 'expr:regex',
    version: '4.1.11',
  },
  {
    name: '$regexMatch',
    value: '$regexMatch',
    firstStage: false,
    score: 1,
    meta: 'expr:regex',
    version: '4.1.11',
  },
  {
    name: '$replaceAll',
    value: '$replaceAll',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '4.4.0',
  },
  {
    name: '$replaceOne',
    value: '$replaceOne',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '4.4.0',
  },
  {
    name: '$reverseArray',
    value: '$reverseArray',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.4.0',
  },
  {
    name: '$second',
    value: '$second',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '2.2.0',
  },
  {
    name: '$setDifference',
    value: '$setDifference',
    firstStage: false,
    score: 1,
    meta: 'expr:set',
    version: '2.6.0',
  },
  {
    name: '$setEquals',
    value: '$setEquals',
    firstStage: false,
    score: 1,
    meta: 'expr:set',
    version: '2.6.0',
  },
  {
    name: '$setIntersection',
    value: '$setIntersection',
    firstStage: false,
    score: 1,
    meta: 'expr:set',
    version: '2.6.0',
  },
  {
    name: '$setIsSubset',
    value: '$setIsSubset',
    firstStage: false,
    score: 1,
    meta: 'expr:set',
    version: '2.6.0',
  },
  {
    name: '$setUnion',
    value: '$setUnion',
    firstStage: false,
    score: 1,
    meta: 'expr:set',
    version: '2.6.0',
  },
  {
    name: '$size',
    value: '$size',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '2.6.0',
  },
  {
    name: '$slice',
    value: '$slice',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.2.0',
  },
  {
    name: '$sortArray',
    value: '$sortArray',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '5.2.0',
  },
  {
    name: '$split',
    value: '$split',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '3.4.0',
  },
  {
    name: '$sqrt',
    value: '$sqrt',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$strcasecmp',
    value: '$strcasecmp',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '2.2.0',
  },
  {
    name: '$strLenBytes',
    value: '$strLenBytes',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '3.4.0',
  },
  {
    name: '$strLenCP',
    value: '$strLenCP',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '3.4.0',
  },
  {
    name: '$substr',
    value: '$substr',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '2.2.0',
    deprecated: '3.4.0',
    replacement: '$substrBytes',
  },
  {
    name: '$substrBytes',
    value: '$substrBytes',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '3.4.0',
  },
  {
    name: '$substrCP',
    value: '$substrCP',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '3.4.0',
  },
  {
    name: '$subtract',
    value: '$subtract',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$switch',
    value: '$switch',
    firstStage: false,
    score: 1,
    meta: 'expr:cond',
    version: '3.4.0',
  },
  {
    name: '$toLower',
    value: '$toLower',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '2.2.0',
  },
  {
    name: '$toUpper',
    value: '$toUpper',
    firstStage: false,
    score: 1,
    meta: 'expr:string',
    version: '2.2.0',
  },
  {
    name: '$tsSecond',
    value: '$tsSecond',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '5.1.0',
  },
  {
    name: '$tsIncrement',
    value: '$tsIncrement',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '5.1.0',
  },
  {
    name: '$trunc',
    value: '$trunc',
    firstStage: false,
    score: 1,
    meta: 'expr:arith',
    version: '3.2.0',
  },
  {
    name: '$type',
    value: '$type',
    firstStage: false,
    score: 1,
    meta: 'expr:type',
    version: '3.4.0',
  },
  {
    name: '$week',
    value: '$week',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '2.2.0',
  },
  {
    name: '$year',
    value: '$year',
    firstStage: false,
    score: 1,
    meta: 'expr:date',
    version: '2.2.0',
  },
  {
    name: '$zip',
    value: '$zip',
    firstStage: false,
    score: 1,
    meta: 'expr:array',
    version: '3.4.0',
  },
] as const;

export { EXPRESSION_OPERATORS };
