/**
 * The query operators.
 */
const QUERY_OPERATORS = [
  {
    name: '$all',
    value: '$all',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$and',
    value: '$and',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$bitsAllClear',
    value: '$bitsAllClear',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '3.2.0',
  },
  {
    name: '$bitsAllSet',
    value: '$bitsAllSet',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '3.2.0',
  },
  {
    name: '$bitsAnyClear',
    value: '$bitsAnyClear',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '3.2.0',
  },
  {
    name: '$bitsAnySet',
    value: '$bitsAnySet',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '3.2.0',
  },
  {
    name: '$comment',
    value: '$comment',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '3.2.0',
  },
  {
    name: '$elemMatch',
    value: '$elemMatch',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$eq',
    value: '$eq',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$exists',
    value: '$exists',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$expr',
    value: '$expr',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '3.6.0',
  },
  {
    name: '$geoIntersects',
    value: '$geoIntersects',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$geoWithin',
    value: '$geoWithin',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$gt',
    value: '$gt',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$gte',
    value: '$gte',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$in',
    value: '$in',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$jsonSchema',
    value: '$jsonSchema',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '3.6.0',
  },
  {
    name: '$lt',
    value: '$lt',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$lte',
    value: '$lte',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$mod',
    value: '$mod',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$ne',
    value: '$ne',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$near',
    value: '$near',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$nearSphere',
    value: '$nearSphere',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$nin',
    value: '$nin',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$not',
    value: '$not',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$nor',
    value: '$nor',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$or',
    value: '$or',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$regex',
    value: '$regex',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$size',
    value: '$size',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$slice',
    value: '$slice',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$text',
    value: '$text',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$type',
    value: '$type',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
  {
    name: '$where',
    value: '$where',
    firstStage: false,
    score: 1,
    meta: 'query',
    version: '2.2.0',
  },
] as const;

export { QUERY_OPERATORS };
